server:
  port: 15000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  address: localhost

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # 更新数据库结构
    show-sql: true
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  # 开启自动映射

#logging:
#  level:
#    org.mybatis: DEBUG
#    org.springframework.jdbc.datasource: DEBUG
#    org.mybatis.spring.SqlSessionFactoryBean: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs  # 这是确保 Swagger UI 能正确获取到文档的配置

